### ISSUE TITLE
May I ask for advice? This error will only appear in the new version.

### ISSUE THREAD

**Issue by PQWAK** [km2ii/JVP_TG-PLUS#123]
May I ask for advice? An error popped up during the runtime, but I have no idea what caused it. This issue did not happen in the previous TGPLUS version.
![27a28f4daab05cc78d89a08f7608660](https://user-images.githubusercontent.com/79788502/227184937-e3d6ce69-3cb3-47da-8820-92c4237c9d0f.png)
![83f67f21a0dfaef515171beb4a9d879](https://user-images.githubusercontent.com/79788502/227184961-76aeaddd-47fc-4e5c-b6c6-7a297514fbe0.png)

**Comment by km2ii** [comment]
The information provided is too few only shows input77 SR failed.
Suggestions:
1. provide the config.ini
2. check the images size in the input77

**Comment by km2ii** [comment]
Normally this is caused by insufficient VRM.
If the error reoccurs, open a command line window: 
```
cd TG/TGMAIN
tgmain.exe 0 TG-STD inputX outputX
```
Check the error message.

**Comment by PQWAK** [comment]
> Normally this is caused by insufficient VRM. If the error reoccurs, open a command line window:
> 
> ```
> cd TG/TGMAIN
> tgmain.exe 0 TG-STD inputX outputX
> ```
> 
> Check the error message.

Thank u, but I have 24GB of VRAM, so it should not be an issue of insufficient VRAM. If I decrease the number of n-count, would that solve the problem?

**Comment by mrsLuPeng** [comment]
I also ran into the same problem, when I executed the command “tgmain.exe 0 TG-STD input0 output0”, the following error occurred "BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead."
![error](https://user-images.githubusercontent.com/102002155/227682663-faea13e1-5c81-466b-8964-3bea14e81e13.png)

Is there any way to solve it?

**Comment by JobNam** [comment]
I had the same problem when I ran the command that "tgmain.exe 0 TG-STD input0 output0" and it came up with a warning and then did nothing.
![error](https://user-images.githubusercontent.com/102002155/227684031-fbba2cd5-dfb1-49b9-bed9-2b815cc5dace.png)
Is there any way to solve it?

**Comment by JobNam** [comment]
> I had the same problem when I ran the command that "tgmain.exe 0 TG-STD input0 output0" and it came up with a warning and then did nothing. ![error](https://user-images.githubusercontent.com/102002155/227684031-fbba2cd5-dfb1-49b9-bed9-2b815cc5dace.png) Is there any way to solve it?

And I'll add the config.ini file
![conf](https://user-images.githubusercontent.com/102002155/227685587-edf66e02-261c-4796-a0b1-2454e144789b.png)

**Comment by km2ii** [comment]
mode = TG ?
TG mode has problem.
Change to TG-PLUS and test again.

**Comment by Great168** [comment]
I also encountered this same problem.
Earlier, I had this problem with the model "tecogan-da\tecoGAN-da-8x-std-ep1", but after I used v0.3.03.20_patcher(20230325) (343.59 KB), tecoGAN-da- 8x-std-ep1 becomes fine.
But later, I switched to using the model basicVSR-pp-8x-std-ep2, and the same problem happened again, that is, there are many photo files in the inputxxx directory, but the outputxxx directory is empty. 

The following is the content of my new config.ini:

[Author]
discord = kmkii#8701
gmail = ty4king@gmail.com

[mplus]
m1 = {'method': 'basicVSR-pp', 'model': 'basicVSR-pp-8x-std-ep2', 'para': '8X'}
m2 = {'method': 'tvai', 'model': 'ahq-12', 'para': '4X'}
memo = This is a memo to note the config applies to scenes, types or other.

[main]
mode = TG-PLUS
debug = OFF

[others]
imgext = jpg
skip_imgs = 14
resolution = 1920
use_sharp1 = False
use_sharp2 = False
fp16 = False
n_count = 30
warm_inter = 5
offset_x = 0
offset_y = 0
crf = 22
dt = 3

[veai]
veaipath = C:/Program Files/Topaz Labs LLC/Topaz Video Enhance AI/veai.exe

[veai_theia_model_opt]
sharpen = 15
enhance-detail = 50
reduce-noise = 0

[veai_proteus_model_opt]
compression = 52
details = 24
blur = 9
noise = 7
halo = 12
preblur = -19

[veaidict]
ahq = ahq-11
alq = alq-12
alqs = alqs-1
amq = amq-12
amqs = amqs-1
gcg = gcg-5
ghq = ghq-5
prob = prob-1
thd = thd-3
thf = thf-4

[tvai]
tvaipath = C:/Program Files/Topaz Labs LLC/Topaz Video AI/Topaz Video AI.exe

[tvai_model_opt]
preblur = 0.0
noise = 0.0
details = 0.0
halo = 0.0
blur = 0.0
compression = 0.0
prenoise = 0.0
grain = 0.0
gsize = 0.0

**Comment by Great168** [comment]
I used v0.3.03.20_patcher(20230325) (343.59 KB)， it work well. Thank you very much

**Comment by testnoMyMe** [comment]
i find the same problem,like @Great168 
and i use the command,have same output.
```
 input shape: [68, 136]
 output shape: [272, 544]
Traceback (most recent call last):
  File "basicVSR-pp.py", line 5, in <module>
  File "core_basicVSR_pp.py", line 1168, in core_basicVSR_pp.main
  File "core_basicVSR_pp.py", line 1171, in core_basicVSR_pp.main
  File "random.py", line 261, in choice
IndexError: Cannot choose from an empty sequence
[8096] Failed to execute script 'basicVSR-pp' due to unhandled exception!
[info] * mPlus m2 - TVAI: skip 0 frames.
```

**Comment by JobNam** [comment]
> mode = TG ? TG mode has problem. Change to TG-PLUS and test again.
Thanks for your answer. Yes, it worked, but when I ran it again there was a new error, so I installed the whole software, now the call to Tecogan succeeded, but failed in the coding phase, the error message is as follows:
![1](https://user-images.githubusercontent.com/102002155/227749925-6b592c03-ead5-4689-baa5-7e14278d777b.png)
The following is the content of my config.ini:
[main]
mode = TG-PLUS
debug = OFF

[mplus]
m1 = {'method': 'tecogan', 'model': 'TG-STD', 'para': '4X'}
m2 = {'method': 'denoise', 'model': 'tla', 'para': 'low'}
memo = This is a memo to note the config applies to scenes, types or other.

[others]
imgext = png
dt = 3
skip_imgs = 14
crf = 22
resolution = 1920
n_count = 60
use_sharp1 = False
use_sharp2 = False
fp16 = False
offset_x = 0
offset_y = 0

[veai]
veaipath = C:/Program Files/Topaz Labs LLC/Topaz Video Enhance AI/veai.exe

[veai_theia_model_opt]
sharpen = 15
enhance-detail = 50
reduce-noise = 0

[veai_proteus_model_opt]
compression = 52
details = 24
blur = 9
noise = 7
halo = 12
preblur = -19

[veaidict]
ahq = ahq-11

[tvai]
tvaipath = C:/Program Files/Topaz Labs LLC/Topaz Video AI/Topaz Video AI.exe

[tvai_model_opt]
preblur = 0
noise = 0
details = 0
halo = 0
blur = 0
compression = 0
prenoise = 0
grain = 0
gsize = 0

[Author]
discord = kmkii#8701
gmail = ty4king@gmail.com

Is there any way to solve this problem, thank you!

**Comment by JobNam** [comment]
> > mode = TG ? TG mode has problem. Change to TG-PLUS and test again.
> 
> Thanks for your answer. Yes, it worked, but when I ran it again there was a new error, so I installed the whole software, now the call to Tecogan succeeded, but failed in the coding phase, the error message is as follows: ![1](https://user-images.githubusercontent.com/102002155/227749925-6b592c03-ead5-4689-baa5-7e14278d777b.png) The following is the content of my config.ini: [main] mode = TG-PLUS debug = OFF
> 
> [mplus] m1 = {'method': 'tecogan', 'model': 'TG-STD', 'para': '4X'} m2 = {'method': 'denoise', 'model': 'tla', 'para': 'low'} memo = This is a memo to note the config applies to scenes, types or other.
> 
> [others] imgext = png dt = 3 skip_imgs = 14 crf = 22 resolution = 1920 n_count = 60 use_sharp1 = False use_sharp2 = False fp16 = False offset_x = 0 offset_y = 0
> 
> [veai] veaipath = C:/Program Files/Topaz Labs LLC/Topaz Video Enhance AI/veai.exe
> 
> [veai_theia_model_opt] sharpen = 15 enhance-detail = 50 reduce-noise = 0
> 
> [veai_proteus_model_opt] compression = 52 details = 24 blur = 9 noise = 7 halo = 12 preblur = -19
> 
> [veaidict] ahq = ahq-11
> 
> [tvai] tvaipath = C:/Program Files/Topaz Labs LLC/Topaz Video AI/Topaz Video AI.exe
> 
> [tvai_model_opt] preblur = 0 noise = 0 details = 0 halo = 0 blur = 0 compression = 0 prenoise = 0 grain = 0 gsize = 0
> 
> [Author] discord = kmkii#8701 gmail = [ty4king@gmail.com](mailto:ty4king@gmail.com)
> 
> Is there any way to solve this problem, thank you!

I'm sorry, it's my fault! GPU0 was set to AMD in my FFmpeg Settings, but actually mine was N Series, I have now changed it, but there is a new error: 
![3](https://user-images.githubusercontent.com/102002155/227751515-9ece7dc1-79ca-4e28-9c1a-04a2f989fe34.png)

does this mean I need to download tvai?

**Comment by Great168** [comment]
> 



> May I ask for advice? An error popped up during the runtime, but I have no idea what caused it. This issue did not happen in the previous TGPLUS version. ![27a28f4daab05cc78d89a08f7608660](https://user-images.githubusercontent.com/79788502/227184937-e3d6ce69-3cb3-47da-8820-92c4237c9d0f.png) ![83f67f21a0dfaef515171beb4a9d879](https://user-images.githubusercontent.com/79788502/227184961-76aeaddd-47fc-4e5c-b6c6-7a297514fbe0.png)

Sorry, I use this package, but I encounter this problem  again.

**Comment by km2ii** [comment]
Again, to check for errors:

> Normally this is caused by insufficient VRM. If the error reoccurs, open a command line window:
> 
> ```
> cd TG/TGMAIN
> tgmain.exe 0 TG-STD inputX outputX
> ```
> 
> **Check the error message.**
