### ISSUE TITLE
cant use models which in TG-MODEL folder directly

### ISSUE THREAD

**Issue by steinvenic** [km2ii/JVP_TG-PLUS#156]
because i dont like windows,so i want to use **TecoGAN** directly with your trined model,but only **TG-STD** works.

SE-4X-R1、SE-4X-S1、UE-4X，dont work
ERRORS:
```
Loading weights from ckpt model
Traceback (most recent call last):
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1378, in _do_call
    return fn(*args)
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1361, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1454, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.DataLossError: not an sstable (bad magic number)
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 255, in <module>
    weight_initiallizer.restore(sess, FLAGS.checkpoint)
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1418, in restore
    sess.run(self.saver_def.restore_op_name,
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 968, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1371, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1397, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.DataLossError: Graph execution error:

Detected at node 'save/RestoreV2' defined at (most recent call last):
    File "main.py", line 234, in <module>
      weight_initiallizer = tf.train.Saver(var_list)
Node: 'save/RestoreV2'
not an sstable (bad magic number)
         [[{{node save/RestoreV2}}]]

Original stack trace for 'save/RestoreV2':
  File "main.py", line 234, in <module>
    weight_initiallizer = tf.train.Saver(var_list)
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 934, in __init__
    self.build()
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 946, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 974, in _build
    self.saver_def = self._builder._build_internal(  # pylint: disable=protected-access
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 543, in _build_internal
    restore_op = self._AddRestoreOps(filename_tensor, saveables,
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 360, in _AddRestoreOps
    all_tensors = self.bulk_restore(filename_tensor, saveables, preferred_shard,
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 611, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1516, in restore_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 795, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/root/miniconda3/envs/python38/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3814, in _create_op_internal
    ret = Operation(
```

**Comment by km2ii** [comment]
Direct calls are not supported.
