### ISSUE TITLE
I tried JVP_1.12b+2.0 v0.3.07.12.

### ISSUE THREAD

**Issue by Great168** [km2ii/JVP_TG-PLUS#179]
Hi
I tried JVP_1.12b+2.0 v0.3.07.12 today.
The following error occurs when I run configtools, where is the error? 
My environment can work in the old version v0.3.03.20_patcher (20230525).
My CPU is AMD 5950, 64G DDR, RTX3060 12G

![Snipaste_2023-07-12_15-14-00](https://github.com/km2ii/JVP_TG-PLUS/assets/128937784/98b7bbe1-be47-454c-bbd4-650ab02caafa)

Traceback (most recent call last):
  File "wmi.py", line 1209, in __getattr__
  File "wmi.py", line 1220, in _cached_classes
  File "<COMObject winmgmts:>", line 2, in Get
  File "win32com\client\dynamic.py", line 366, in _ApplyTypes_
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, 'SWbemServicesEx', '找不到 ', None, 0, -2147217406), None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\RECYCLER\S-1-5-21-1801674531-1275210071-1644681000-500\com1.{d3e34b21-9d75-101a-8c3d-00aa001a1652}\ã..\Disks\Z\Data\javplayer\build_20230705\ConfigTools\main.py", line 3, in <module>
  File "_configTools.py", line 614, in init _configTools
  File "_configTools.py", line 525, in _configTools.register.check_register
  File "_configTools.py", line 498, in _configTools.register.getCombinNumber
  File "_configTools.py", line 486, in _configTools.register.get_CPU_info
  File "wmi.py", line 1211, in __getattr__
  File "win32com\client\dynamic.py", line 638, in __getattr__
AttributeError: winmgmts:.Win32_Processor

**Comment by Great168** [comment]
I have tried to apply the aptcher, v.03.07.12_patcher(20230713), not it still does not work.
