### ISSUE TITLE
Error when opening ConfigTools.exe - ImportError: Module use of python37.dll conflicts with this version of Python.

### ISSUE THREAD

**Issue by SyntaxError1871** [km2ii/JVP_TG-PLUS#191]
Is there any way to change the python version for ConfigTools.exe? I don't want to change it since that will probably break other applications I use currently using this version of Python.

Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 58, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 42, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 9, in <module>
ImportError: Module use of python37.dll conflicts with this version of Python.

![image](https://github.com/km2ii/JVP_TG-PLUS/assets/48274164/56d5c038-e1c7-4183-bedb-c6ffba50cdec)

**Comment by SyntaxError1871** [comment]
You can close - solved by following these steps:

https://github.com/km2ii/JVP_TG-PLUS/issues/178#issuecomment-1633726096

**Comment by SyntaxError1871** [comment]
Closing issue - solved by https://github.com/km2ii/JVP_TG-PLUS/issues/178#issuecomment-1633726096
